name: to_doc_patient
description: This app can be used to book an appointment from doctor.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.1
  fluttertoast: ^8.0.3
  flutter_secure_storage: ^4.1.0
  email_validator: '^1.0.6'
  cached_network_image: ^3.0.0
  url_launcher: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
